### PR TITLE
Don't fail if the mocked function is not found, as long as there's a mock

### LINKED ISSUE #11: Allow mocking a function that isn't linked into the exe
When linking a test executable, we sometimes don't want to link it with all the libraries that are used in production. Mocking is very useful for this - if you mock all functions in a library, you don't need to link with the library itself. But C-mock searches for the real function with `dlsym`, and fails if it doesn't exist. So you have to link with it.

In my company linkage is a mess, so we have a local change that checks if the function exists only if we actually try to call it. This is very useful for us.
You can see the code in [a branch in my clone](https://github.com/hjagodzinski/C-Mock/compare/master...ugoren:allow_no_real).

But this changes behavior unconditionally, so I don't think it's appropriate for merge.

The only difficulty is how can we make it conditional. There are may alternatives, such as:

- Compile time switch (e.g. `make ALLOW_MISSING=1`).
- A separate set of macros (e.g. `CMOCK_MOCK_FUNCTIONn_ALLOW_MISSING`).
- When using a mock class, a variation of `CMockMocker` (e.g. `CMockMockerAllowMissing`).
- A macro defined by used before defining mocks (e.g. `#define CMOCK_ALLOW_MISSING 1`).

Can we add this functionality?

Thanks.

### PR DESCRIPTION
**Pull request by ugoren**
Fixes #11

### CODE REVIEW

File: include/cmock/cmock-function-class-mockers.h.pump [hunk 1]
```diff
@@ -72,18 +72,9 @@ T *CMockMocker<T>::instance = NULL;
 
 // Find the real implementation of a mocked function
 static inline void *
-cmock_lookup(const char *fname, const void *mock_addr)
+cmock_lookup(const char *fname, const void *)
```
Comment (hjagodzinski) [inline include/cmock/cmock-function-class-mockers.h.pump]: Since the second argument is no more used may you remove it altogether?

File: include/cmock/cmock-function-class-mockers.h.pump [hunk 2]
```diff
@@ -104,6 +95,12 @@ GMOCK_RESULT_(, F) n($declare_args) { \
         return mock->n($call_args); \
     } \
 	\
+    if (__cmock_real_##c##_##n == NULL) { \
+        std::ostringstream msg; \
```
Comment (hjagodzinski) [inline include/cmock/cmock-function-class-mockers.h.pump]: What do you think about changing the message to _Error: Function #n not found. Neither mock nor real function is present._

File: include/cmock/cmock-function-class-mockers.h.pump [hunk 3]
```diff
@@ -104,6 +95,12 @@ GMOCK_RESULT_(, F) n($declare_args) { \
...
+        msg << "Error: Function " << #n; \
+        msg << " not found - both mock and real function are missing"; \
+        throw std::logic_error(msg.str()); \
```
Comment (hjagodzinski) [inline include/cmock/cmock-function-class-mockers.h.pump]: Would you mind adding an unit test on this?

File: include/cmock/cmock-function-class-mockers.h.pump (hunk 2 above)
Comment (ugoren) [reply include/cmock/cmock-function-class-mockers.h.pump]: Done
